/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DecentralizedExchangeGUI.java
 *
 * Created on 20.03.2015, 21:34:20
 */
package de.bitcrystal.decentralizedexchange;

import java.io.File;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ABC
 */
public class DecentralizedExchangeGUI extends javax.swing.JFrame {

    private static String currentTradeAddressS;
    private static String currentTradeWithAddressS;
    private static boolean isInit = false;
    private static boolean processProcessed = false;
    private static boolean canSetTradeWithAddress = true;

    /** Creates new form DecentralizedExchangeGUI */
    public DecentralizedExchangeGUI() {
        initComponents();
        bitcoinBalanceLabel.setVisible(false);
        bitcrystalBalanceLabel.setVisible(false);
        bitcoinBalance.setVisible(false);
        bitcrystalBalance.setVisible(false);
        depositAddressForBitcoinsLabel.setVisible(false);
        depositAddressForBitcrystal.setVisible(false);
        depositAddressBitcoins.setVisible(false);
        depositAddressBitcrystal.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        currentTradeAddress = new javax.swing.JTextField();
        currentTradeWithAddress = new javax.swing.JTextField();
        getNewCurrentTradeAddressButton = new javax.swing.JButton();
        currentTradeWithAddressButton = new javax.swing.JButton();
        depositAddressForBitcoinsLabel = new javax.swing.JLabel();
        depositAddressForBitcrystal = new javax.swing.JLabel();
        depositAddressBitcoins = new javax.swing.JTextField();
        depositAddressBitcrystal = new javax.swing.JTextField();
        bitcoinBalanceLabel = new javax.swing.JLabel();
        bitcrystalBalanceLabel = new javax.swing.JLabel();
        bitcoinBalance = new javax.swing.JTextField();
        bitcrystalBalance = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel2.setText("CurrentTradeAddress");
        jLabel2.setName(""); // NOI18N

        jLabel3.setText("CurrentTradeWithAddress");

        currentTradeAddress.setEditable(false);
        currentTradeAddress.setText("jTextField1");
        currentTradeAddress.setName(""); // NOI18N

        currentTradeWithAddress.setText("jTextField1");

        getNewCurrentTradeAddressButton.setText("Get Current Trade Address");
        getNewCurrentTradeAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNewCurrentTradeAddressButtonActionPerformed(evt);
            }
        });

        currentTradeWithAddressButton.setText("Set Current Trade With Address");
        currentTradeWithAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentTradeWithAddressButtonActionPerformed(evt);
            }
        });

        depositAddressForBitcoinsLabel.setText("Deposit Address For Bitcoins");

        depositAddressForBitcrystal.setText("Deposit Address For Bitcrystal");

        depositAddressBitcoins.setEditable(false);
        depositAddressBitcoins.setText("jTextField1");

        depositAddressBitcrystal.setEditable(false);
        depositAddressBitcrystal.setText("jTextField1");

        bitcoinBalanceLabel.setText("Bitcoin Balance");

        bitcrystalBalanceLabel.setText("Bitcrystal Balance");

        bitcoinBalance.setEditable(false);
        bitcoinBalance.setText("jTextField1");
        bitcoinBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitcoinBalanceActionPerformed(evt);
            }
        });
        bitcoinBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bitcoinBalanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bitcoinBalanceFocusLost(evt);
            }
        });

        bitcrystalBalance.setEditable(false);
        bitcrystalBalance.setText("jTextField2");
        bitcrystalBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitcrystalBalanceActionPerformed(evt);
            }
        });
        bitcrystalBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bitcrystalBalanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bitcrystalBalanceFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(depositAddressForBitcoinsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentTradeAddress, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(getNewCurrentTradeAddressButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(depositAddressBitcoins, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addGap(24, 24, 24))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(bitcoinBalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bitcoinBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(currentTradeWithAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(currentTradeWithAddressButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(depositAddressForBitcrystal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depositAddressBitcrystal, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bitcrystalBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bitcrystalBalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentTradeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentTradeWithAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getNewCurrentTradeAddressButton)
                    .addComponent(currentTradeWithAddressButton))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositAddressForBitcoinsLabel)
                    .addComponent(depositAddressForBitcrystal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositAddressBitcoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositAddressBitcrystal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bitcoinBalanceLabel)
                    .addComponent(bitcrystalBalanceLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bitcrystalBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bitcoinBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleParent(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void getNewCurrentTradeAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNewCurrentTradeAddressButtonActionPerformed
    if (!isInit) {
        JOptionPane.showMessageDialog(null, "The Decentralized Exchange Server is not initialized. Please wait a minute or two!");
        return;
    }
    DecentralizedExchange.start();
    currentTradeAddressS = ClientConnection.getCurrentTradeAddress();
    currentTradeAddress.setText(currentTradeAddressS);
}//GEN-LAST:event_getNewCurrentTradeAddressButtonActionPerformed

private void currentTradeWithAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentTradeWithAddressButtonActionPerformed

    if (!isInit) {
        JOptionPane.showMessageDialog(null, "The Decentralized Exchange Server is not initialized. Please wait a minute or two!");
        return;
    }
    if (processProcessed) {
        JOptionPane.showMessageDialog(null, "The Process is working! Please be patient!");
        return;
    }
    if (!canSetTradeWithAddress) {
        JOptionPane.showMessageDialog(null, "In order to change the current trade with address you must restart the client!");
        return;
    }

    JOptionPane.showMessageDialog(null, "The Process takes a while! Please wait a minute or two!");
    new NotInterruptableThread(new Runnable() {

        public void run() {
            processProcessed = true;

            currentTradeWithAddressS = currentTradeWithAddress.getText();
            DecentralizedExchange.command("tradewith " + currentTradeWithAddressS);
            if (ClientConnection.getLastCommandStatus()) {
                currentTradeWithAddress.setEditable(false);
                currentTradeWithAddressS = ClientConnection.getCurrentTradeWithAddress();
                currentTradeAddress.setText(currentTradeAddressS);
                canSetTradeWithAddress = false;
                processProcessed = false;
                bitcoinBalance.setVisible(true);
                bitcrystalBalance.setVisible(true);
                bitcoinBalanceLabel.setVisible(true);
                bitcrystalBalanceLabel.setVisible(true);
                depositAddressForBitcoinsLabel.setVisible(true);
                depositAddressForBitcrystal.setVisible(true);
                depositAddressBitcoins.setVisible(true);
                depositAddressBitcrystal.setVisible(true);
                String tradeAccountMultisigAddressForBitcoin = ClientConnection.getTradeAccountMultisigAddressForBitcoin();
                String tradeAccountMultisigAddressForBitcrystal = ClientConnection.getTradeAccountMultisigAddressForBitcrystal();
                depositAddressBitcoins.setText(tradeAccountMultisigAddressForBitcoin);
                depositAddressBitcrystal.setText(tradeAccountMultisigAddressForBitcrystal);
                JOptionPane.showMessageDialog(null, "Successfully setted the current trade with address to " + currentTradeWithAddressS + "!");
            } else {
                processProcessed = false;
                JOptionPane.showMessageDialog(null, "Error ! The Address is not contains in the database of the node server!");
                return;
            }
        }
    }).start();


}//GEN-LAST:event_currentTradeWithAddressButtonActionPerformed

private void bitcoinBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitcoinBalanceActionPerformed
    double balance = ClientConnection.getBitcoinBalanceTradeAccount();
    if (balance <= 0) {
        balance = 0;
    }
    bitcoinBalance.setText("" + balance);
}//GEN-LAST:event_bitcoinBalanceActionPerformed

private void bitcoinBalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bitcoinBalanceFocusGained
    double balance = ClientConnection.getBitcoinBalanceTradeAccount();
    if (balance <= 0) {
        balance = 0;
    }
    bitcoinBalance.setText("" + balance);
}//GEN-LAST:event_bitcoinBalanceFocusGained

private void bitcrystalBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitcrystalBalanceActionPerformed
    double balance = ClientConnection.getBitcrystalBalanceTradeAccount();
    if (balance <= 0) {
        balance = 0;
    }
    bitcrystalBalance.setText("" + balance);
}//GEN-LAST:event_bitcrystalBalanceActionPerformed

private void bitcrystalBalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bitcrystalBalanceFocusGained
    double balance = ClientConnection.getBitcrystalBalanceTradeAccount();
    if (balance <= 0) {
        balance = 0;
    }
    bitcrystalBalance.setText("" + balance);
}//GEN-LAST:event_bitcrystalBalanceFocusGained

private void bitcoinBalanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bitcoinBalanceFocusLost
    double balance = ClientConnection.getBitcoinBalanceTradeAccount();
    if (balance <= 0) {
        balance = 0;
    }
    bitcoinBalance.setText("" + balance);
}//GEN-LAST:event_bitcoinBalanceFocusLost

private void bitcrystalBalanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bitcrystalBalanceFocusLost
    double balance = ClientConnection.getBitcrystalBalanceTradeAccount();
    if (balance <= 0) {
        balance = 0;
    }
    bitcrystalBalance.setText("" + balance);
}//GEN-LAST:event_bitcrystalBalanceFocusLost
    private static String commandParser(String command) {
        String ret = "";
        try {
            ret = new String(command.getBytes("UTF-8"), "UTF-8");
        } catch (Exception ex) {
            ret = "";
        }
        return ret;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecentralizedExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecentralizedExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecentralizedExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecentralizedExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NotInterruptableThread(
                        new Runnable() {

                            public void run() {
                                new DecentralizedExchangeGUI().setVisible(true);
                                DecentralizedExchange.start();
                                new File("client.properties").delete();
                                try {
                                    DecentralizedExchange.command("tradeabort");
                                    DecentralizedExchange.command("add");
                                    isInit = true;
                                } catch (Exception ex) {
                                    JOptionPane.showMessageDialog(null, "Cannot connect to the node server please change the node.properties and restart the client!");
                                    System.exit(0);
                                    return;
                                }
                            }
                        }).start();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bitcoinBalance;
    private javax.swing.JLabel bitcoinBalanceLabel;
    private javax.swing.JTextField bitcrystalBalance;
    private javax.swing.JLabel bitcrystalBalanceLabel;
    private javax.swing.JTextField currentTradeAddress;
    private javax.swing.JTextField currentTradeWithAddress;
    private javax.swing.JButton currentTradeWithAddressButton;
    private javax.swing.JTextField depositAddressBitcoins;
    private javax.swing.JTextField depositAddressBitcrystal;
    private javax.swing.JLabel depositAddressForBitcoinsLabel;
    private javax.swing.JLabel depositAddressForBitcrystal;
    private javax.swing.JButton getNewCurrentTradeAddressButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
